package com.example.ipro_hr.payload;

public enum BotState {
    ENTER,
    START,
    REGISTRATION,
    FIRST_NAME,
    LAST_NAME,
    PROFESSION,
    USER_PHONE_NUMBER,
    LOCATION,
    LEVEL,
    PORTFOLIO,
    SALARY,
    EMPLOYMENT_TYPE,
    SEND_CV,
    INCORRECT_PHONE,
    SEND_DATA_TO_CHANNEL,
    REGISTRATION_FINISHED,
    CONFIRM_PAYMENT,
    ALREADY_REGISTRATED
}
