package com.example.ipro_hr.payload;

public enum BotState {
    ENTER,
    START,
    REGISTRATION,
    FULL_NAME,

    //KASB NOMINI YUBORISH
    PROFESSION,
    USER_PHONE_NUMBER,
    //Notug'ri raqam

    LOCATION,

    //DARAJA
    LEVEL,
    PORTFOLIO,
    SALARY,
    EMPLOYMENT_TYPE,
    SEND_CV,
//    PHOTO,
INCORRECT_PHONE,
    SEND_DATA_TO_CHANNEL,
    REGISTRATION_FINISHED,
    CONFIRM_PAYMENT,
//    CONFIRM_PAYMENT,
    ALREADY_REGISTRATED
}
